default:
  outputs:
    dev:
      type: postgres
      host: '{{ env_var("DBT_HOST") }}'
      user: '{{ env_var("DBT_USER") }}'
      password: '{{ env_var("DBT_PASSWORD") }}'
      port: 5432
      dbname: '{{ env_var("DBT_DATABASE") }}'
      schema: dev
  target: dev
